# -*- coding: utf-8 -*-
"""Data_BF_with_All_Foundation_Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiJIRX6uC2zEAP2G1HHOOCuq_f2GnSRv

# Install Required Libraries for Foundation Models
"""

import subprocess

pip_packages = [
    "transformers>=4.46.0",
    "accelerate",
    "chronos-forecasting",
    "lag-llama",
    "huggingface_hub",
    "tsfm-public",
    "uni2ts",
    "gluonts",
    "google-generativeai"
]

for pkg in pip_packages:
    subprocess.run(["pip", "install", "-q"] + pkg.split(), check=False)

print("All packages installed. RESTART the runtime before continuing if in Colab.")

"""# Delhi Climate Data — Data Preparation

"""

import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import STL
from sklearn.metrics import mean_squared_error, r2_score
import torch
import warnings
warnings.filterwarnings("ignore")

# Load and Prep
df = pd.read_csv('DailyDelhiClimateTrain.csv')
df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)
df = df.asfreq('D')

# ── STL Decomposition (EDA — full series, before split or preprocessing) ───────
stl = STL(df['meantemp'].dropna(), period=365, robust=True)
stl_fit = stl.fit()
stl_fit.plot()
plt.suptitle('STL Decomposition — Delhi Mean Temperature', y=1.02)
plt.tight_layout()
plt.show()
print(f"Trend range:    {stl_fit.trend.min():.1f} – {stl_fit.trend.max():.1f} °C")
print(f"Seasonal range: {stl_fit.seasonal.min():.1f} – {stl_fit.seasonal.max():.1f} °C")
print(f"Residual std:   {stl_fit.resid.std():.4f}")

# ── ADF Stationarity Test ─────────────────────────────────────────────────────
from statsmodels.tsa.stattools import adfuller

def run_adf(series, label):
    result = adfuller(series.dropna(), autolag='AIC')
    stat, p, lags, _, crit, _ = result
    is_stationary = p < 0.05
    print(f"\n--- ADF Test: {label} ---")
    print(f"  ADF Statistic : {stat:.4f}")
    print(f"  p-value       : {p:.4f}")
    print(f"  Lags used     : {lags}")
    print(f"  Critical values: 1%={crit['1%']:.3f}, 5%={crit['5%']:.3f}, 10%={crit['10%']:.3f}")
    print(f"  -> {'STATIONARY' if is_stationary else 'NOT STATIONARY'}")
    return is_stationary

raw_series = df['meantemp'].dropna()
is_stationary = run_adf(raw_series, "Raw meantemp")

if not is_stationary:
    diff_series = raw_series.diff().dropna()
    run_adf(diff_series, "1st-order Differenced meantemp")

    fig, axes = plt.subplots(2, 1, figsize=(14, 6), sharex=True)
    axes[0].plot(raw_series.index, raw_series, color='steelblue', linewidth=1)
    axes[0].set_title('Original meantemp (Non-Stationary)')
    axes[0].set_ylabel('C')
    axes[1].plot(diff_series.index, diff_series, color='darkorange', linewidth=1)
    axes[1].set_title('1st-Difference meantemp (Stationary)')
    axes[1].set_ylabel('Delta C')
    plt.tight_layout()
    plt.show()
    print("\nNote: Foundation models receive the original series (they handle non-stationarity internally).")
else:
    print("\nSeries is stationary — no differencing needed.")

# ── SPLIT FIRST (before any preprocessing to prevent data leakage) ─────────────
split_idx = int(len(df) * 0.8)
train = df.iloc[:split_idx].copy()
test  = df.iloc[split_idx:].copy()
print(f"Train samples: {len(train)}, Test samples: {len(test)}")

# ── Outlier handling: thresholds derived from TRAIN only ───────────────────────
# meanpressure: physically impossible values — domain threshold safe for both splits
for split_df in [train, test]:
    mask = (split_df["meanpressure"] < 900) | (split_df["meanpressure"] > 1100)
    split_df.loc[mask, "meanpressure"] = np.nan
    split_df["meanpressure"] = split_df["meanpressure"].interpolate().ffill().bfill()

# IQR bounds computed from TRAIN only → applied to both splits (no leakage)
for col in ["meantemp", "humidity", "wind_speed"]:
    Q1, Q3 = train[col].quantile([0.25, 0.75])
    IQR = Q3 - Q1
    lower, upper = Q1 - 1.5 * IQR, Q3 + 1.5 * IQR
    for split_df in [train, test]:
        split_df.loc[(split_df[col] < lower) | (split_df[col] > upper), col] = np.nan
        split_df[col] = split_df[col].interpolate().ffill().bfill()

# ── Feature Engineering (after split & outlier cleaning — no leakage) ──────────
def add_features(df_split, train_tail=None):
    """train_tail: last N rows of train, seeds rolling features for test."""
    combined = pd.concat([train_tail, df_split]) if train_tail is not None else df_split.copy()

    combined['month']       = combined.index.month
    combined['day_of_year'] = combined.index.day_of_year
    combined['sin_doy']     = np.sin(2 * np.pi * combined['day_of_year'] / 365)
    combined['cos_doy']     = np.cos(2 * np.pi * combined['day_of_year'] / 365)

    for lag in [1, 7, 14]:
        combined[f'temp_lag_{lag}'] = combined['meantemp'].shift(lag)

    for window in [7, 30]:
        combined[f'temp_rollmean_{window}'] = combined['meantemp'].shift(1).rolling(window).mean()
        combined[f'temp_rollstd_{window}']  = combined['meantemp'].shift(1).rolling(window).std()

    return combined.iloc[len(train_tail):] if train_tail is not None else combined

SEED_ROWS  = 30
train_feat = add_features(train).dropna()
test_feat  = add_features(test, train_tail=train.iloc[-SEED_ROWS:])

# ── Metrics helpers ─────────────────────────────────────────────────────────────
def calc_smape(actual, predicted):
    denom = (np.abs(actual) + np.abs(predicted)) / 2.0 + 1e-8
    return float(np.mean(np.abs(actual - predicted) / denom) * 100)

def calc_rmse(actual, predicted):
    return np.sqrt(mean_squared_error(actual, predicted))

def store_metrics(results_dict, name, actual, preds):
    results_dict[name] = {
        'MSE':   mean_squared_error(actual, preds),
        'RMSE':  calc_rmse(actual, preds),
        'sMAPE': calc_smape(actual, preds),
        'R2':    r2_score(actual, preds),
        'preds': np.array(preds),
    }

results = {}
actual  = test['meantemp'].values

"""# Foundation Models Forecasting

"""

# ── Collect full preprocessed train as FM context (zero-shot, no training) ─────
ctx_vals         = train['meantemp'].values.astype(np.float32)
test_values      = test['meantemp'].values.astype(np.float32)
FORECAST_HORIZON = len(test)
ROLLING_STEP     = 14

print(f"Context length: {len(ctx_vals)} days")
print(f"Forecast Horizon: {FORECAST_HORIZON} days")
print(f"Rolling step: {ROLLING_STEP} days")

def rolling_forecast(model_fn, ctx_full, test_vals_arr, step=ROLLING_STEP, ctx_cap=512):
    """Walk-forward: predict `step` days at a time, updating context with actuals."""
    preds = []
    ctx = list(ctx_full)
    for i in range(0, len(test_vals_arr), step):
        horizon = min(step, len(test_vals_arr) - i)
        chunk = model_fn(np.array(ctx[-ctx_cap:], dtype=np.float32), horizon)
        preds.extend(chunk[:horizon])
        ctx.extend(test_vals_arr[i : i + horizon])
    return np.array(preds, dtype=np.float32)

"""### 1. Amazon Chronos-T5-Tiny

"""

from chronos import ChronosPipeline

chronos_tiny = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-tiny",
    device_map="cuda" if torch.cuda.is_available() else "cpu",
    torch_dtype=torch.bfloat16
)

TINY_CTX_CAP = 512

def chronos_tiny_fn(ctx_window, horizon):
    mu, sigma = ctx_window.mean(), ctx_window.std() + 1e-8
    ctx_norm = torch.tensor((ctx_window - mu) / sigma, dtype=torch.float32)
    fc = chronos_tiny.predict(ctx_norm, prediction_length=horizon, num_samples=20)
    return fc.median(dim=1).values.squeeze().numpy() * sigma + mu

pred_tiny = rolling_forecast(chronos_tiny_fn, ctx_vals, test_values, ctx_cap=TINY_CTX_CAP)
store_metrics(results, 'Chronos-T5-Tiny', actual, pred_tiny)
print("Chronos-Tiny RMSE:", results['Chronos-T5-Tiny']['RMSE'])
del chronos_tiny

"""### 2. Amazon Chronos-T5-Small

"""

chronos_small = ChronosPipeline.from_pretrained(
    "amazon/chronos-t5-small",
    device_map="cuda" if torch.cuda.is_available() else "cpu",
    torch_dtype=torch.bfloat16
)

SMALL_CTX_CAP = 2048

def chronos_small_fn(ctx_window, horizon):
    mu, sigma = ctx_window.mean(), ctx_window.std() + 1e-8
    ctx_norm = torch.tensor((ctx_window - mu) / sigma, dtype=torch.float32)
    fc = chronos_small.predict(ctx_norm, prediction_length=horizon, num_samples=20)
    return fc.median(dim=1).values.squeeze().numpy() * sigma + mu

pred_small = rolling_forecast(chronos_small_fn, ctx_vals, test_values, ctx_cap=SMALL_CTX_CAP)
store_metrics(results, 'Chronos-T5-Small', actual, pred_small)
print("Chronos-Small RMSE:", results['Chronos-T5-Small']['RMSE'])
del chronos_small

"""### 3. Amazon Chronos-Bolt-Small

"""

from chronos import BaseChronosPipeline

chronos_bolt = BaseChronosPipeline.from_pretrained(
    "amazon/chronos-bolt-small",
    device_map="cuda" if torch.cuda.is_available() else "cpu",
    torch_dtype=torch.bfloat16
)

BOLT_CTX_CAP = 512

def chronos_bolt_fn(ctx_window, horizon):
    mu, sigma = ctx_window.mean(), ctx_window.std() + 1e-8
    ctx_norm = torch.tensor((ctx_window - mu) / sigma, dtype=torch.float32)
    fc = chronos_bolt.predict(ctx_norm, prediction_length=horizon)
    return fc.median(dim=1).values.squeeze().numpy() * sigma + mu

pred_bolt = rolling_forecast(chronos_bolt_fn, ctx_vals, test_values, ctx_cap=BOLT_CTX_CAP)
store_metrics(results, 'Chronos-Bolt-Small', actual, pred_bolt)
print("Chronos-Bolt RMSE:", results['Chronos-Bolt-Small']['RMSE'])
del chronos_bolt

from gluonts.dataset.common import ListDataset
from gluonts.dataset.field_names import FieldName

"""### 4. Lag-Llama (time-series-foundation-models/Lag-Llama)

"""

from huggingface_hub import hf_hub_download
from lag_llama.gluon.estimator import LagLlamaEstimator

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

lagllama_ckpt = hf_hub_download(
    repo_id="time-series-foundation-models/Lag-Llama",
    filename="lag-llama.ckpt"
)

lagllama_estimator = LagLlamaEstimator(
    ckpt_path=lagllama_ckpt,
    prediction_length=ROLLING_STEP,
    context_length=512,
    nonnegative_pred_samples=True,
    aug_prob=0,
    device=device,
    batch_size=1,
    num_parallel_samples=100,
)
lagllama_predictor = lagllama_estimator.create_predictor()

def lagllama_fn(ctx_window, horizon):
    ds = ListDataset([{
        FieldName.TARGET: ctx_window,
        FieldName.START: pd.Period("2016-01-01", freq="D"),
    }], freq="D")
    forecasts = list(lagllama_predictor.predict(ds))
    return np.median(forecasts[0].samples, axis=0).astype(np.float32)[:horizon]

pred_lagllama = rolling_forecast(lagllama_fn, ctx_vals, test_values, ctx_cap=512)
store_metrics(results, 'Lag-Llama', actual, pred_lagllama)
print("Lag-Llama RMSE:", results['Lag-Llama']['RMSE'])
del lagllama_predictor

"""### 5. TinyTimeMixer (ibm-granite/granite-timeseries-ttm-r2-512-96)

"""

from tsfm_public.models.tinytimemixer import TinyTimeMixerForPrediction

TTM_CTX = 512

ttm_model = TinyTimeMixerForPrediction.from_pretrained(
    "ibm-granite/granite-timeseries-ttm-r2-512-96"
)
ttm_model = ttm_model.to(device)
ttm_model.eval()

def ttm_fn(ctx_window, horizon):
    ctx_raw = ctx_window[-TTM_CTX:]
    if len(ctx_raw) < TTM_CTX:
        ctx_raw = np.pad(ctx_raw, (TTM_CTX - len(ctx_raw), 0), mode="edge")
    x = torch.tensor(ctx_raw, dtype=torch.float32).unsqueeze(0).unsqueeze(-1).to(device)
    with torch.no_grad():
        output = ttm_model(past_values=x)
    return output.prediction_outputs.squeeze().cpu().numpy().astype(np.float32)[:horizon]

pred_ttm = rolling_forecast(ttm_fn, ctx_vals, test_values, ctx_cap=TTM_CTX)
store_metrics(results, 'TinyTimeMixer', actual, pred_ttm)
print("TinyTimeMixer RMSE:", results['TinyTimeMixer']['RMSE'])
del ttm_model

"""### 6. Moirai (Salesforce/moirai-1.0-R-base)

"""

from uni2ts.model.moirai import MoiraiForecast, MoiraiModule

moirai_module = MoiraiModule.from_pretrained("Salesforce/moirai-1.0-R-base")
moirai_model = MoiraiForecast(
    module=moirai_module,
    prediction_length=ROLLING_STEP,
    context_length=512,
    patch_size="auto",
    num_samples=20,
    target_dim=1,
    feat_dynamic_real_dim=0,
    past_feat_dynamic_real_dim=0,
)
moirai_predictor = moirai_model.create_predictor(
    batch_size=4,
    device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
)

moirai_preds_list = []
ctx_rolling = list(ctx_vals)
for i in range(0, len(test_values), ROLLING_STEP):
    horizon = min(ROLLING_STEP, len(test_values) - i)
    ctx_window = np.array(ctx_rolling[-512:], dtype=np.float32)
    chunk_start_date = test.index[i] - pd.Timedelta(days=len(ctx_window))
    ds = ListDataset([{
        FieldName.TARGET: ctx_window,
        FieldName.START: pd.Period(chunk_start_date, freq="D"),
    }], freq="D")
    fcsts = list(moirai_predictor.predict(ds))
    moirai_preds_list.extend(fcsts[0].samples.mean(axis=0).astype(np.float32)[:horizon])
    ctx_rolling.extend(test_values[i : i + horizon])

moirai_preds = np.array(moirai_preds_list, dtype=np.float32)
store_metrics(results, 'Moirai', actual, moirai_preds)
print("Moirai RMSE:", results['Moirai']['RMSE'])
del moirai_model, moirai_predictor

"""### 7. All Models Comparison

"""

comparison_df = pd.DataFrame({
    'Model':     list(results.keys()),
    'MSE':       [results[m]['MSE']   for m in results],
    'RMSE':      [results[m]['RMSE']  for m in results],
    'sMAPE (%)': [results[m]['sMAPE'] for m in results],
    'R2':        [results[m]['R2']    for m in results],
}).sort_values('RMSE').reset_index(drop=True)

print(comparison_df.to_string(index=False))

plt.figure(figsize=(16, 6))
plt.plot(test.index, actual, color='black', label='Actual', linewidth=2)

plot_colors = {
    'Chronos-T5-Tiny': '#2196F3', 'Chronos-T5-Small': '#8BC34A',
    'Chronos-Bolt-Small': '#FF9800', 'Lag-Llama': '#E91E63',
    'TinyTimeMixer': '#9C27B0', 'Moirai': '#00BCD4'
}

for model_name in results:
    plt.plot(test.index, results[model_name]['preds'], label=model_name,
             color=plot_colors.get(model_name, 'gray'), linewidth=1.2,
             linestyle='--', alpha=0.8)

plt.title('Foundation Models — Rolling 14-day Forecast vs Actual', fontsize=14)
plt.xlabel('Date')
plt.ylabel('Mean Temperature (°C)')
plt.legend()
plt.tight_layout()
plt.show()

# ── Individual Chart per Model ────────────────────────────────────────────────
n_models = len(results)
n_cols = min(n_models, 3)
n_rows = math.ceil(n_models / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(6 * n_cols, 5 * n_rows),
                         sharex=True, sharey=True)
axes = np.array(axes).flatten()

for i, model_name in enumerate(results):
    ax = axes[i]
    rmse_val = results[model_name]['RMSE']
    ax.plot(test.index, actual, color='black', label='Actual', linewidth=2)
    ax.plot(test.index, results[model_name]['preds'],
            color=plot_colors.get(model_name, 'gray'),
            label=model_name, linewidth=1.4, linestyle='--', alpha=0.85)
    ax.set_title(f"{model_name}  |  RMSE: {rmse_val:.2f}C", fontsize=10)
    ax.set_ylabel('Temp (C)')
    ax.legend(fontsize=7)
    ax.tick_params(axis='x', rotation=30)

for j in range(i + 1, len(axes)):
    axes[j].set_visible(False)

fig.suptitle('Each Foundation Model vs Actual — Test Period', fontsize=14, y=1.02)
plt.tight_layout()
plt.show()

"""### 8. Gemini LLM Analysis

"""

from google import genai

GEMINI_API_KEY = "YOUR_API_KEY_HERE"  # Put your key here before running
client = genai.Client(api_key=GEMINI_API_KEY)

best_model_name    = comparison_df.iloc[0]['Model']
best_model_metrics = comparison_df[comparison_df['Model'] == best_model_name].iloc[0]

prompt = f"""You are a climate data analyst. A time-series forecasting model has produced a {FORECAST_HORIZON}-day forecast of daily mean temperature in Delhi (°C).

Here are the actual vs predicted values for the test period:
- Actual temperatures (°C): {actual.tolist()}
- Forecasted temperatures (°C): {[round(v, 2) for v in results[best_model_name]['preds'].tolist()]}
- Forecast dates: {[str(d.date()) for d in test.index.tolist()]}

Explain what this forecast tells us about Delhi's temperature during the test period:
1. What is the overall temperature trend — rising, falling, or stable?
2. Are there noticeable fluctuations or spikes? When do they occur?
3. How closely does the forecast follow the actual temperature pattern?
4. What would someone reading this forecast conclude about Delhi's climate during this period?

Speak as if explaining to a city planner or journalist — no technical jargon, no model names, no metric scores. Focus entirely on what the forecast reveals about the temperature.
"""

try:
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    print("--- Gemini LLM Analysis ---\n")
    print(response.text)
except Exception as e:
    print("Gemini Analysis failed (Make sure to add your API key):", e)
